# Default values for finops-cratedb-cluster-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/krateoplatformops/crate
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

openshift:
  enabled: false
# Pre-install job configuration
  preInstallJob:
    # Image to use for running OpenShift CLI commands
    image: "quay.io/openshift/origin-cli:4.16"
    # Additional parameters for the job
    ttlSecondsAfterFinished: 300

serviceAccount:
  create: true
  name: ""  # If not set, the chart name is used
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"

securityContext:
  capabilities:
    add:
    - SYS_CHROOT
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  privileged: true
  runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# livenessProbe:
#   httpGet:
#     path: /health
#     port: http
# readinessProbe:
#   httpGet:
#     path: /health
#     port: http

volumes:
  - name: create-user
    configMap:
      name: create-user-sidecar
      defaultMode: 0755

volumeMounts: 
- mountPath: /data
  name: data
- mountPath: /scripts
  name: create-user

volumeClaims:
- metadata:
    name: data
  spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: azurefile-csi
    resources:
      requests:
        storage: 128Mi
crate:
  heapsize: "1g"
  adminUser: crate
  newUser: system

metadata:
  annotations: {}  # This will override any default annotations
  labels: {}      # This will override any default labels

env: {}

