{{- if .Values.openshift.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ include "finops-cratedb-cluster-chart.fullname" . }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}-scc
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - rolebindings
  verbs:
  - create
  - get
  - update
{{- end }}
