apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}-secret-creator
  labels:
    {{- include "finops-cratedb-cluster-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}-secret-creator
subjects:
- kind: ServiceAccount
  name: {{ include "finops-cratedb-cluster-chart.serviceAccountName" . }}