apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}-secret-creator
  labels:
    {{- include "finops-cratedb-cluster-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "udpate", "patch"]