kind: Service
apiVersion: v1
metadata:
  name: {{ include "cratedb.fullname" . }}-internal
  labels:
    {{- include "cratedb.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # A static IP address is assigned to this service. This IP address is
  # only reachable from within the Kubernetes cluster.
  type: ClusterIP
  ports:
    # Port 4300 for inter-node communication.
  - port: 4300
    name: crate-internal
  selector:
    {{- include "cratedb.labels" . | nindent 4 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "cratedb.fullname" . }}
  labels:
    {{- include "cratedb.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # Create an externally reachable load balancer.
  type: {{ .Values.service.type }}
  ports:
    # Port 4200 for HTTP clients.
  - port: {{ .Values.service.httpPort }}
    name: crate-web
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.httpPort }}
    {{- end }}
    # Port 5432 for PostgreSQL wire protocol clients.
  - port: {{ .Values.service.postgreSQLPort }}
    name: postgres
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.postgreSQLPort }}
    {{- end }}
  selector:
    {{- include "cratedb.labels" . | nindent 4 }}