kind: Service
apiVersion: v1
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}
  labels:
    {{- include "finops-cratedb-cluster-chart.labels" . | nindent 4 }}
spec:
  # Create an externally reachable load balancer.
  type: LoadBalancer
  ports:
    # Port 4200 for HTTP clients.
  - port: 4200
    name: crate-web
    # Port 5432 for PostgreSQL wire protocol clients.
  - port: 5432
    name: postgres
  selector:
    {{- include "finops-cratedb-cluster-chart.labels" . | nindent 4 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "finops-cratedb-cluster-chart.fullname" . }}-internal
  labels:
    {{- include "finops-cratedb-cluster-chart.labels" . | nindent 4 }}
spec:
  # A static IP address is assigned to this service. This IP address is
  # only reachable from within the Kubernetes cluster.
  type: ClusterIP
  ports:
    # Port 4300 for inter-node communication.
  - port: 4300
    name: crate-internal
  selector:
    {{- include "finops-cratedb-cluster-chart.labels" . | nindent 4 }}